### ISSUE TITLE
Nil safety

### ISSUE THREAD

**Issue by kajacx** [teal-language/tl#831] opened 2024-10-17 12:22 UTC
Are there any plans to add proper `nil`-safety? From the tutorial page: 

> Every type in Teal accepts nil as a valid value, even if, like in Lua, attempting to use it with some operations would cause a runtime error, so be aware!

I believe this is a big mistake as you don't know which variables are `nil`-able and which aren't. Let's say are writing a function. Will callers pass `nil` as an argument? You don't know. Can you pass a variable from an object as an argument to another function? Again, even if it has the same type (both are `string` for example), you don't know! The object flield might be `nil`-able, but the function might expect a non-`nil`-able argument, resulting in a crash at runtime! This is just awful, so, are there any plans to add proper `nil` checking, like `null` and `undefined` strict check in TypeScript?

**Comment by hishamhm** [comment] 2024-10-17 12:36
> I believe this is a big mistake

[You are not alone](https://en.wikipedia.org/wiki/Tony_Hoare#Research_and_career), [we all agree](https://www.youtube.com/watch?v=HfnjUCRzRKU). :)

This is the next big thing on my radar.

Closing this as a duplicate of #598.

**Closed by hishamhm** 2024-10-17 12:36 UTC
Labels: semantics
