### ISSUE TITLE
Implementation of 'new' keyword

### ISSUE THREAD

**Issue by NotSoSeriouss** [teal-language/tl#690] opened 2023-09-03 13:55 UTC
I know that this might be not so important but it might also make some code cleaner. I already took a look at #638 and realized how important is the existance for both static functions and methods inside of records. But I think a cleaner way of working with methods will also lead to cleaner code:

Right now if I want to create a constructor I have to do it this way:

``` lua
local record Point
    x: integer
    y: integer
    new: function(x: integer, y: integer) : Point -- Constructor
end

function Point.new(x: integer, y: integer) : Point -- Constructor definition
    local self: Point = setmetatable({}, {__index = Point})
    self.x = x
    self.y = y
    return self
end

```

And to create a new method:

``` lua
local record Point
    x: integer
    y: integer
    new: function(x: integer, y: integer) : Point
    incrementX: function(self: Point, n: integer) -- Method declaration
end
```
And
``` lua
function Point:incrementX(n: integer) -- Method definition
    self.x = self.x + n
end
```

But I propose a different way of building constructors and methods:

To make a constructor for an object we can simply declare a function with the same name of the record. This shouldn't cause any compatibiliy issues since Teal already doesn't allow that. But instead of giving an error, this:

``` lua
local record Point
    x: integer
    y: integer
end

function Point(x: integer, y: integer)
    self.x = x
    self.y = y
end
```

Could get automatically compiled as if it were:
``` lua
local record Point
    x: integer
    y: integer
    new: function(x: integer, y: integer) : Point
end

function Point.new(x: integer, y: integer) : Point
    local self: Point = setmetatable({}, {__index = Point})
    self.x = x
    self.y = y
    return self
end
```

And if there is no declaration of the constructor, then this would be the case:
``` lua
local record Point
    x: integer
    y: integer
    new: function() : Point
end
```

This can allow for a nice improvement: the use of `new`
``` lua
local record Point
    x: integer
    y: integer
end

local a: Point = new Point()
-- Or even
local a: Point = new() -- Since the type is already known
```
which is only shugar syntax for:
``` lua
local a: Point = Point.new()
```

**Comment by NotSoSeriouss** [comment] 2023-09-03 13:57
About methods: I didn't include the part about methods because this is already too munch by itself so I didn't want to overload the proposal. But it would work in a similar way by using the keyword "method" instead of "function" in the declaration inside the record. Just like how #638 proposed so I didn't want to repeat that.

**Comment by NotSoSeriouss** [comment] 2023-09-03 14:10
Just realized this is a kind of duplicate of #200. I will leave the issue open just in case

**Comment by hishamhm** [comment] 2023-09-04 20:49
@NotSoSeriouss Yes, this is a duplicate of #200 and #97. I'm going to close this one, but these references will create backlinks at the open issues so that your comments can be found from there as well.

**Closed by hishamhm** 2023-09-04 20:49 UTC
Labels: duplicate, feature request
