### ISSUE TITLE
Error: could not predefine module 'love-example'

### ISSUE THREAD

**Issue by gloirekiba** [teal-language/tl#660] opened 2023-05-17 02:25 UTC
I have been following teal tutorial, i am trying to make my custom predefine module, so for that i took the `love` from the tutorial, but when running `tl build` or `tl check main.tl` i get this error

Error: could not predefine module 'love-example'

![Screenshot from 2023-05-17 04-21-26](https://github.com/teal-language/tl/assets/94308564/528a150d-fde1-476a-8d94-38b5fca46442)

**Comment by gloirekiba** [comment] 2023-05-17 14:18
Update:
It work when using the command as super user `sudo tl build` looks like teal only work when installed globally

**Comment by hishamhm** [comment] 2023-05-17 14:33
@gloirekiba it should work without `sudo`. Make sure the permissions in your files are correct and all paths are reachable.

Also, `tl build` is deprecated, please use https://github.com/teal-language/cyan as your build manager!

**Comment by gloirekiba** [comment] 2023-05-17 16:50
My permissions and path are correct, and i can invoke teal from everywhere since it is in the $PATH, but vscode-teal is the only one not able to find teal, it require me to install teal globally

![Screenshot from 2023-05-17 18-39-37](https://github.com/teal-language/tl/assets/94308564/7dac7f70-96d9-493a-a635-afc8d0d387e7)

![Screenshot from 2023-05-17 18-49-31](https://github.com/teal-language/tl/assets/94308564/d26747b3-2b83-4b3a-9b37-bf26352ab02c)


Thanks i did not know about cyan, i am gonna check

**Comment by lenscas** [comment] 2023-05-18 00:20
> My permissions and path are correct, and i can invoke teal from everywhere since it is in the $PATH, but vscode-teal is the only one not able to find teal, it require me to install teal globally

I had similar problems with Ruby's tooling some time ago, with it working flawlessly everywhere but vscode. The problem is related to how vscode spawns as it doesn't take over the environment entirely from your terminal nor runs the exact same files to setup the environment as your terminal does.

So, if I had to guess the local luarocks bin folder is set to be added to the $PATH but that the line to do that is in a file that vscode doesn't run.

**Comment by hishamhm** [comment] 2023-05-18 18:46
In addition, your `love-example.d.tl` doesn't seem to be in a location that matches Lua/Teal module search paths. Lua does have `./?.lua` by default (which Teal auto-translates to `./?.tl` and `./?.d.tl` for its own search when there's no separate `TL_PATH` env variable defined), but something weird may be going on due to vscode environment variables. You may want to try to explicitly add the folder to the search list in your tlconfig.lua using `include_dir = { "/folder/where/my/files/are" }`, this might do the trick.

Hope this helps. I'll close this issue since I think this is more of a local configuration issue rather than an actual bug in `tl`.

**Closed by hishamhm** 2023-05-18 18:46 UTC

**Comment by musjj** [comment] 2025-03-20 11:55
I'm still having this issue unfortunately, here's a reproduction repository: https://github.com/musjj/teal-env-bug

Running `cyan build` results into:

```bash
Error Could not initialize Teal environment:
  ... Error: could not predefine module 'love'
```

I tried moving `love.d.tl` inside `src`, but it still errors out. So I don't think this is a VS Code issue.

**Comment by Andre-LA** [comment] 2025-03-20 14:29
@musjj  I clonned your repository now and for me `cyan build` works.

My teal version: 0.24.4

**Comment by musjj** [comment] 2025-03-20 16:33
Hmmm, is there a way to debug this? I'm on NixOS, so there may be something funny going on with the paths, but I can't tell what.

**Comment by Andre-LA** [comment] 2025-03-20 19:28
There is a debug flag on cyan, I think is `--verbose debug` (I can't look now)

Try running `cyan build --help` to check the flag.
