### ISSUE TITLE
tl failed to compare types

### ISSUE THREAD

**Issue by virusdefender** [teal-language/tl#452] opened 2021-06-11 03:34 UTC
`a.tl`

```
local errors = require("errors")

local M = {}
function M.x():err_t
    return errors.new("x")
end

return M
```

`errors.tl`

```
local M = {}

global record err_t
end

function M.new(msg: string): err_t
    return msg as err_t
end

return M
```

`tlconfig.lua`

```
return {}
```

and then `cp a.tl f.tl && tl build  -b __build__`

tl will throw some errors

```
Wrote: __build__/a.lua
Wrote: __build__/errors.lua
========================================
1 error:
f.tl:5:22: in return value: err_t (defined in ./errors.tl:3) is not a err_t (defined in errors.tl:3)
```

if you rename `a.tl` to some name like `z.tl`, it will work.

**Comment by hishamhm** [comment] 2022-08-09 22:54
Does it also happen if you build with https://github.com/teal-language/cyan instead of `tl build`?

**Comment by hishamhm** [comment] 2022-08-09 22:59
I tried the steps above with `tl build`, and I cannot reproduce with the latest master of `tl`. Closing this one; feel free to reopen if the problem persists.

**Closed by hishamhm** 2022-08-09 22:59 UTC
Labels: bug
