### ISSUE TITLE
<unknown type> error when calling module as a function?

### ISSUE THREAD

**Issue by pdesaulniers** [teal-language/tl#86] opened 2020-04-05 14:51 UTC
I'm trying to use a declaration file for `inspect.lua`, but I'm getting an `<unknown type>` error when I call the `inspect` function. Here's a simplified test case:

`inspect.d.tl`:
```lua
local inspect: function(value: any, options: any): string
return inspect
```

`test.tl`:
```lua
local inspect = require "inspect"
inspect(123)
```

`tl check test.tl`:
```
1 error:
test.tl:2:1: not a function: <unknown type>
```

**Comment by hishamhm** [comment] 2020-04-06 04:48
(Sending from the phone)

I need to check this error message, but the problem is that your inspect
definition is returning a functiontype declaration, and not a function.

Same thing happens in the json definition you sent on teal-types: that is
returning a record _type_, not a record. I wonder why that didn't fail on
use, it probably should have the same way this functiontype did!

>

**Comment by pdesaulniers** [comment] 2020-04-06 13:27
Not sure if you saw my edit on GitHub.  I believe I'm returning an uninitialized variable of type 'function' now:
```lua
local inspect: function(value: any, options: any): string
return inspect
```

> Same thing happens in the json definition you sent on teal-types: that is
returning a record _type_, not a record. 

Ah, so it's a feature, and not a bug? :stuck_out_tongue: I assumed that "record" declarations also created a table. Personally, this behavior is intuitive to me:

`point.tl`
```lua
local Point = record
	x: number
	y: number
end

local PointMetatable: METATABLE = {
	__index = Point
}

local function Point.new(x: number, y: number): Point
	local self = setmetatable({}, PointMetatable) as Point

	self.x = x or 0
	self.y = y or 0

	return self
end

function Point.move(self: Point, dx: number, dy: number)
	self.x = self.x + dx 
	self.y = self.y + dy
end

return Point
```

`main.tl`
```lua
local Point = require("point")
local x: Point = Point.new(1, 2)
```

**Comment by hishamhm** [comment] 2020-04-08 23:15
> Ah, so it's not supposed to work? :stuck_out_tongue:

Eh... it wasn't the original plan: I intended to keep a distinction between type and non-type values (because that distinction might be useful in the future). The type compiles to a `{}` because I wanted the name to bind to a value in Lua code, and I've been thinking about storing type metadata in the type value, possibly allowing for runtime checks from pure Lua code or reflection. But that could always be stored elsewhere too.

But yeah, reviewing the code and the tests, that's how I ended up implementing it to make this kind of "prototype-based" behavior work when extending records.

Let's keep this as is for now. I'm not very happy with the handling of metatables yet — it's barely there, and the compiler generally ignores anything "smart" that is done with metatables, and most of these "smart" things are very dynamic will be impossible for tl to understand at compile-time anyway. (I think that's one of the reasons that TypeScript went for an actual class model on top of JS, and that's a thought that crosses my mind every now and then because Lua also doesn't have a standardized one.)

**Comment by hishamhm** [comment] 2020-04-08 23:16
> Here's a simplified test case:

I can't reproduce it on the latest master! Your example typechecks fine here.

**Comment by hishamhm** [comment] 2020-04-08 23:16
(note that if you happen to have a file `inspect.tl` in the same directory, it will pick that up instead... perhaps that's what's happening?)

**Comment by pdesaulniers** [comment] 2020-04-09 22:17
Actually, I see that `./tl check test.tl` typechecks fine, but `tl check test.tl` throws the error. Is my system badly configured?

**Comment by hishamhm** [comment] 2020-04-10 00:42
@pdesaulniers Maybe you have tl 0.1 installed in your system via `luarocks install tl`? Try `luarocks remove tl` then `sudo luarocks make` in the dev repo to install the latest master.

**Comment by hishamhm** [comment] 2020-04-10 14:21
@pdesaulniers I'd say let's close this one for now, and if the problem persists, feel free to reopen, but I think you probably have an old version around!

**Closed by hishamhm** 2020-04-10 14:21 UTC

**Comment by pdesaulniers** [comment] 2020-04-11 01:55
@hishamhm Oops, looks like you're right! I did a `luarocks purge --local` and reinstalled the latest master. It typechecks fine now.
