### ISSUE TITLE
[next branch] `where` conflicts with `<total>`

### ISSUE THREAD

**Issue by Andre-LA** [teal-language/tl#749] opened 2024-06-07 18:56 UTC
Code to reproduce:

```lua
local interface Op
	op: string
end

local interface Binary
	is Op
	left: number
	right: number
end

local record Add
	is Binary
	-- where self.op == '+' -- removing the comment triggers an error
end

local sum <total>: Add = {
	op = '+',
	left = 10,
	right = 20
}

print(sum.op, sum.left, sum.right)
```

**Comment by hishamhm** [comment] 2024-06-07 19:19
This is happening because the presence of any metamethod (even the `__is` pseudo-metamethod that is implied by `where`) is currently marking a table as non-total:

https://github.com/teal-language/tl/blob/master/tl.tl#L9015-L9017

The intention was that `<total>` was only defined for "known-to-be-well-behaved" types (after all you can do all sorts of crazy things with metamethods). Maybe that was just being overzealous from my part. Simply removing that check makes this case pass. I'm now wondering whether I should just remove it, or if I should downgrade it to something to "check for the presence of `__index` and/or `__newindex`").

**Comment by Andre-LA** [comment] 2024-06-07 19:44
To be honest I generally rely on `new` functions to ensure the initialization of tables are correct, because of this I don't use `<total>` often for records (I found this one by accident while testing).

Maybe should records also has the `foo?: number` syntax? like that:

```lua
local record Foo
	bar: number
	baz?: number
end

local foo: Foo = {
	bar = 10
	-- compiler accepts no baz initialization because it's "baz?"
}

print(foo.bar, foo.baz)
```

So the advantage of "init-checking" is preserved, the optional init is available and can be manually specified case by case, and `<total>` could be constrained just on of the original maps-of-enums use case you cited on my previous report.

**Comment by Frityet** [comment] 2024-06-27 20:33
> To be honest I generally rely on `new` functions to ensure the initialization of tables are correct, because of this I don't use `<total>` often for records (I found this one by accident while testing).
> 
> Maybe should records also has the `foo?: number` syntax? like that:
> 
> ```lua
> local record Foo
> 	bar: number
> 	baz?: number
> end
> 
> local foo: Foo = {
> 	bar = 10
> 	-- compiler accepts no baz initialization because it's "baz?"
> }
> 
> print(foo.bar, foo.baz)
> ```
> 
> So the advantage of "init-checking" of `<total>` is preserved, the optional init is available and can be manually specified case by case, and `<total>` could be constrained just on the original maps-of-enums use case you cited on my previous report.
> 
> The downside I suppose is backward compatibility, since it would start checking keys presence (without `<total>`) unlike before.

optional record members is something that would help so much, in general I wish we had nillable types, but at least optional record members would be nice

**Comment by hishamhm** [comment] 2024-08-07 20:39
Fixed in `next`, with a regression test added. Thank you for the report! (And yes, I want to add a nil-strict mode in the future!)

**Closed by hishamhm** 2024-08-07 20:39 UTC
Labels: semantics
