### ISSUE TITLE
"bad argument to ipairs" in compiler 0.14.0

### ISSUE THREAD

**Issue by mrjones2014** [teal-language/tl#552] opened 2022-08-17 21:05 UTC
building with 0.13.2 works fine but with 0.14.0 I get:

```
.luarocks/share/lua/5.1/compat53/module.lua:179: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
	[C]: in function 'ipairs'
	...ary.nvim/.luarocks/share/lua/5.1/compat53/module.lua:179: in function 'ipairs'
	...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:5534: in function 'is_valid_union'
	...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:9036: in function 'cbkind_after'
	...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:3351: in function 'recurse'
	...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:3160: in function 'fn'
	...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:3342: in function 'recurse'
	...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:3171: in function 'fn'
	...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:3342: in function 'recurse'
	...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:3160: in function 'fn'
	...
	...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:3342: in function 'recurse'
	...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:3160: in function 'fn'
	...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:3342: in function <...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:3322>
	(tail call): ?
	...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:9418: in function 'type_check'
	...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:9799: in function <...y.nvim/legendary.nvim/.luarocks/share/lua/5.1/tl.lua:9756>
	(tail call): ?
	.../.luarocks/lib/luarocks/rocks-5.1/tl/0.14.0-1/bin/tl:1181: in function '?'
	.../.luarocks/lib/luarocks/rocks-5.1/tl/0.14.0-1/bin/tl:1410: in main chunk
	[C]: ?
make: *** [Makefile:19: check-teal] Error 1
```

GitHub Actions job: https://github.com/mrjones2014/legendary.nvim/runs/7887544767?check_suite_focus=true

**Comment by hishamhm** [comment] 2022-08-17 23:26
Thanks for the report! This is a duplicate of #551 and it's already fixed in `master`. A new release should be coming shortly!

**Closed by hishamhm** 2022-08-17 23:27 UTC
Labels: duplicate
