### ISSUE TITLE
0.15.1: incorrect redeclaration warning regression

### ISSUE THREAD

**Issue by lewis6991** [teal-language/tl#620] opened 2023-01-24 13:53 UTC
```lua

local record B
  contains : function(M, bufnr: integer, start: integer, last: integer): boolean
  on_lines : function(M, bufnr: integer, first: integer, last_orig: integer, last_new: integer)
  reset    : function(M)
end

local M: B = {}

function M:contains(bufnr: integer, start: integer, last: integer): boolean
end

function M:on_lines(_: integer, _: integer, _: integer, _: integer)
end

function M:reset()
end
```

Gives warnings:
```
teal/gitsigns/signs/vimfn.tl:84:1: redeclaration of function 'on_lines'
teal/gitsigns/signs/vimfn.tl:147:1: redeclaration of function 'contains'
teal/gitsigns/signs/vimfn.tl:156:1: redeclaration of function 'reset'
```

Changing to `M.on_lines = function()...` works around the issue.

**Comment by hishamhm** [comment] 2023-01-25 02:03
@lewis6991 I couldn't reproduce the issue with the test case above. Could you double check the example? Thank you!

**Comment by lewis6991** [comment] 2023-01-25 12:38
Ok, the issue was quite a bit more nuanced. Here's a minimal reproducer:

`base.tl`:
```lua
local record M
  foo: function(M)
end

return M
```

`t1.tl`:
```lua
local B = require('base')

local M: B = {}

function M:foo()
end

return M
```

`t2.tl`:
```lua
local B = require('base')

local M: B = {}

function M:foo()
end

return M
```

`top.tl`:
```lua
local B = require('gitsigns.signs.base')

local cond = true

local function new(_: any, _: string): B
  local C: B
  if cond then
    C = require('t1')
  else
    C = require('t2')
  end
end

return new
```

Warning:
```
t2.tl:5:1: redeclaration of function 'foo'
```

**Comment by hishamhm** [comment] 2023-01-25 23:23
@lewis6991 Thank you for the complete regression test! I pushed a fix.

**Closed** 2023-01-25 23:23 UTC
Labels: bug
