### ISSUE TITLE
missing warning: mismatch signature about optional declaration

### ISSUE THREAD

**Issue by fperrad** [teal-language/tl#822] opened 2024-10-14 19:49 UTC
there is a warning for mismatch about type, but nothing about optional declaration

```
local record Foo
    bar: function (v1: number, v2: number): number
    baz: function (v1: integer, v2?: integer): integer
end

function Foo.bar (v1: number, v2: integer): number  -- type signature of 'bar' does not match its declaration in Foo: argument 2: got integer, expected number
    return v1 + v2
end

function Foo.baz (v1: integer, v2: integer): integer  -- [[EXPECTED WARNING]] type signature of 'baz' does not match its declaration in Foo: argument 2: got mandatory, expected optional
    return v1 + v2
end
```

**Comment by hishamhm** [comment] 2024-10-14 20:07
This is a duplicate of #788. I was wondering whether this should be a hard error, but I'm inclined to agree that a `warning` should suffice.

**Closed by hishamhm** 2024-10-14 20:07 UTC
