### ISSUE TITLE
Add a way to disable automatically added std declarations

### ISSUE THREAD

**Issue by ggoraa** [teal-language/tl#658] opened 2023-05-14 00:33 UTC
Some systems that embed Lua and can't use a lot of std functionality just drop the thing entirely and make their own thing. One example is the [EdgeTX](https://github.com/EdgeTX/edgetx) firmware, where Lua only has access to some of the built in libraries, like `table` and `string`, while a lot of other functionality was removed for compatibility reasons, and any needed functionality is redefined as their own API. Oh, and some standard libraries even have their API altered. Again, compatibility reasons.

I think it will be good to add an option to disable those declarations, so that it can be made as a custom type declaration file.

**Comment by hishamhm** [comment] 2023-05-15 13:23
This is a duplicate of #532, and something I've started looking at!

**Closed by hishamhm** 2023-05-15 13:23 UTC
