### ISSUE TITLE
wrong `tl gen` output dir

### ISSUE THREAD

**Issue by virusdefender** [teal-language/tl#236] opened 2020-10-16 09:19 UTC
if you run `tl gen a/b/c/d.tl`, `d.lua` will appear in current dir instead of `a/b/c/d.lua`

related code

```lua
local function get_output_filename(file_name)
   local tail = file_name:match("[^%" .. path_separator .. "]+$")
   if not tail then
      return
   end
   local name, ext = tail:match("(.+)%.([a-zA-Z]+)$")
   if not name then name = tail end
   if ext ~= "lua" then
      return  name .. ".lua"
   else
      return name .. ".out.lua"
   end
end
```

**Comment by euclidianAce** [comment] 2020-10-16 09:37
This is currently the intended behavior to emulate how other compilers like `gcc` and `clang` work. To specify where the output goes you can use the `-o --output` flag
```
tl gen a/b/c/d.tl -o a/b/c/d.lua
```
If you'd like more control over where files end up, use a `Makefile` or `tl build` with a `tlconfig.lua` in the root of your project.

**Comment by virusdefender** [comment] 2020-10-16 10:20
ok, i'm using some script like `find . -type f \( -name "*.tl" \! -name "*.d.tl" \) -not -path "./tl/*" | xargs tl gen --skip-compat53`

it seems `tl build` is a new command

**Comment by virusdefender** [comment] 2020-10-19 03:22
> This is currently the intended behavior to emulate how other compilers like `gcc` and `clang` work. To specify where the output goes you can use the `-o --output` flag
> 
> ```
> tl gen a/b/c/d.tl -o a/b/c/d.lua
> ```
> 
> If you'd like more control over where files end up, use a `Makefile` or `tl build` with a `tlconfig.lua` in the root of your project.

`tl build` will fail on my code https://github.com/teal-language/tl/issues/245

**Comment by euclidianAce** [comment] 2020-11-04 04:58
Closing this as everything (in this issue) seems to be resolved

**Closed by euclidianAce** 2020-11-04 04:58 UTC
